### ISSUE TITLE
Problems after executing commands

### ISSUE THREAD

**Issue by joaopaulo-web** [markshust/magento2-module-pagebuildersourcecode#10]
I'm using Magento 2.4.6 and PHP 8.1

When I execute the comand _composer require markshust/magento2-module-pagebuildersourcecode_, this give me back some errors:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - markshust/magento2-module-pagebuildersourcecode 1.0.0 requires magento/framework 102.0.1.* -> could not be found in any version, there may be a typo in the package name.
    - markshust/magento2-module-pagebuildersourcecode 1.0.1 requires magento/framework 102.0.* -> could not be found in any version, there may be a typo in the package name.
    - markshust/magento2-module-pagebuildersourcecode 1.0.2 requires php ^7.1 -> your php version (8.1.12) does not satisfy that requirement.
    - markshust/magento2-module-pagebuildersourcecode[1.0.3, ..., 1.0.4] require magento/framework >=100 -> could not be found in any version, there may be a typo in the package name.
    - Root composer.json requires markshust/magento2-module-pagebuildersourcecode * -> satisfiable by markshust/magento2-module-pagebuildersourcecode[1.0.0, ..., 1.0.4].

There's a way to solve this?

**Comment by markshust** [comment]
I'm sorry, I'm unable to replicate this so I'm closing out this ticket.
