### ISSUE TITLE
Missing insert widget button within page builder text element toolbar. 

### ISSUE THREAD

**Issue by carlos-reynosa** [markshust/magento2-module-pagebuildersourcecode#3]
Before installing this extension i was able to insert a magento widget within a text page builder element by selecting a insert widget button within the toolbar. After installing the extension i no longer see the button. 

Possible relevant files:

* \Magento\Tinymce3\Model\Config\Widget\Config.php
*  lib/web/mage/adminhtml/wysiwyg/tiny_mce/plugins/magentowidget/editor_plugin.js

Some useful keywords:

* magentowidget

The following changes seem to have overwritten whatever plugins install additional buttons to the toolbars:
![Screenshot from 2020-12-03 14-51-07](https://user-images.githubusercontent.com/926773/101098222-6bbf1f80-3577-11eb-9d5a-e9b87b3bd65c.png)

**Comment by carlos-reynosa** [comment]
Just adding 'magentowidget' seems to work.

**Comment by markshust** [comment]
This presents an interesting architectural problem. I'd probably need to see the module's code, but I'm not sure if it's a problem worth pursuing. Probably best just to create/add to your own `adminhtml/di.xml` file, using this module's example, and add the `magentowidget` item to the string.
