### ISSUE TITLE
Doesn't work with PHP 7.4

### ISSUE THREAD

**Issue by serhii-chernenko** [markshust/magento2-module-pagebuildersourcecode#4]
I can't install the module for M2.4.2 with PHP7.4

**Comment by SukeshiniR** [comment]
I also couldn't install the plugin on Magento CE 2.3.4 with PHP 7.2

**Comment by markshust** [comment]
I just pushed up version 1.0.3 with a new version constraint format... can you both let me know if it works for you now?

**Comment by serhii-chernenko** [comment]
> I just pushed up version 1.0.3 with a new version constraint format... can you both let me know if it works for you now?

yep, now it works for m2.4.2 and php7.4. thanks!
screenshot: https://tppr.me/SfxHU
