### ISSUE TITLE
Missing insert variable button within page builder text element toolbar.

### ISSUE THREAD

**Issue by yurirn** [markshust/magento2-module-pagebuildersourcecode#8]
Before installing this extension i was able to insert a magento variable within a text page builder element by selecting a insert variable button within the toolbar. After installing the extension i no longer see the button.

whats the code to call the button in adminhtml/di.xml?

@markshust can u help me?

**Comment by markshust** [comment]
Thanks for the report. I confirmed that not only is the "Insert variable" icon missing, but so are the "Special character" and "Insert Widget" icons.

I'm still trying to find out why this is happening.

**Comment by GamesmenJordan** [comment]
Couldn't figure out the cause either, but using a plugin to insert the toolbar change instead worked and didn't cause these buttons to go missing.

```php
class PageBuilderWysiwygConfigProviderPlugin {
    public function afterGetConfig(\Magento\PageBuilder\Model\Wysiwyg\DefaultConfigProvider $subject, \Magento\Framework\DataObject $result) {
        $tinymce = $result->getData('tinymce4');
        $tinymce['toolbar'] .= ' | code';
        $result->setData('tinymce4', $tinymce);
        return $result;
    }
}
```

It's not as clean as a single file, but at least it works.

**Comment by stephen-larkbury** [comment]
Can confirm the issue is also present in Magento 2.4.4 EE
